# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-19 20:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Directors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=1000)),
                ('tmdbId', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=1000)),
                ('tmdbId', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MovieCollections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(default='', max_length=128)),
                ('title', models.CharField(default='', max_length=1000)),
                ('adult_content', models.BooleanField(default=0)),
                ('hide_unseen_titles', models.BooleanField(default=0)),
                ('title_language', models.CharField(default='en', max_length=2)),
                ('poster_language', models.CharField(default='-', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdbId', models.IntegerField(default=0)),
                ('release', models.IntegerField(default=0)),
                ('note', models.FloatField(default=0)),
                ('original_language', models.CharField(default='', max_length=4)),
                ('directors', models.ManyToManyField(to='api.Directors', verbose_name='list_of_directors')),
                ('genres', models.ManyToManyField(to='api.Genres', verbose_name='list_of_genres')),
            ],
        ),
        migrations.CreateModel(
            name='Networks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=1000)),
                ('tmdbId', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Posters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(default='', max_length=200)),
                ('language', models.CharField(default='', max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='SeenMovies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen', models.BooleanField(default=0)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.MovieCollections')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Movies')),
            ],
        ),
        migrations.CreateModel(
            name='SeenTVShows',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Titles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=1000)),
                ('language', models.CharField(default='', max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='TVShowCollections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(default='', max_length=128)),
                ('title', models.CharField(default='', max_length=1000)),
                ('adult_content', models.BooleanField(default=0)),
                ('hide_unseen_titles', models.BooleanField(default=0)),
                ('title_language', models.CharField(default='en', max_length=2)),
                ('poster_language', models.CharField(default='-', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='TVShows',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdbId', models.IntegerField(default=0)),
                ('note', models.FloatField(default=0)),
                ('original_language', models.CharField(default='', max_length=4)),
                ('genres', models.ManyToManyField(to='api.Genres', verbose_name='list_of_genres')),
                ('networks', models.ManyToManyField(to='api.Networks', verbose_name='list_of_directors')),
                ('posters', models.ManyToManyField(to='api.Posters', verbose_name='list_of_posters')),
                ('titles', models.ManyToManyField(to='api.Titles', verbose_name='list_of_titles')),
            ],
        ),
        migrations.AddField(
            model_name='tvshowcollections',
            name='content',
            field=models.ManyToManyField(related_name='collection_tv_shows', to='api.TVShows', verbose_name='list_of_tv_shows'),
        ),
        migrations.AddField(
            model_name='seentvshows',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.TVShowCollections'),
        ),
        migrations.AddField(
            model_name='seentvshows',
            name='tv_show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.TVShows'),
        ),
        migrations.AddField(
            model_name='movies',
            name='posters',
            field=models.ManyToManyField(to='api.Posters', verbose_name='list_of_posters'),
        ),
        migrations.AddField(
            model_name='movies',
            name='titles',
            field=models.ManyToManyField(to='api.Titles', verbose_name='list_of_titles'),
        ),
        migrations.AddField(
            model_name='moviecollections',
            name='content',
            field=models.ManyToManyField(related_name='collection_movies', to='api.Movies', verbose_name='list_of_movies'),
        ),
    ]
