# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 18:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Directors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=1000)),
                ('tmdbId', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=1000)),
                ('tmdbId', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MovieCollections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=1000)),
                ('hash', models.CharField(default='', max_length=128)),
                ('adult_content', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=1000)),
                ('tmdbId', models.IntegerField(default=0)),
                ('release', models.IntegerField(default=0)),
                ('note', models.FloatField(default=0)),
                ('poster', models.CharField(default='', max_length=200)),
                ('directors', models.ManyToManyField(to='api.Directors', verbose_name='list_of_directors')),
                ('genres', models.ManyToManyField(to='api.Genres', verbose_name='list_of_genres')),
            ],
        ),
        migrations.CreateModel(
            name='SeenMovies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen', models.BooleanField(default=0)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.MovieCollections')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Movies')),
            ],
        ),
        migrations.AddField(
            model_name='moviecollections',
            name='movies',
            field=models.ManyToManyField(related_name='collection_movies', to='api.Movies', verbose_name='list_of_movies'),
        ),
    ]
