# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-11 12:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeenTVShows',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TVShowCollections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=1000)),
                ('hash', models.CharField(default='', max_length=128)),
                ('adult_content', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TVShows',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=1000)),
                ('tmdbId', models.IntegerField(default=0)),
                ('note', models.FloatField(default=0)),
                ('poster', models.CharField(default='', max_length=200)),
                ('directors', models.ManyToManyField(to='api.Directors', verbose_name='list_of_directors')),
                ('genres', models.ManyToManyField(to='api.Genres', verbose_name='list_of_genres')),
            ],
        ),
        migrations.RenameField(
            model_name='moviecollections',
            old_name='movies',
            new_name='content',
        ),
        migrations.AddField(
            model_name='tvshowcollections',
            name='content',
            field=models.ManyToManyField(related_name='collection_movies', to='api.TVShows', verbose_name='list_of_movies'),
        ),
        migrations.AddField(
            model_name='seentvshows',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.TVShowCollections'),
        ),
        migrations.AddField(
            model_name='seentvshows',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.TVShows'),
        ),
    ]
