# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-25 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.TextField(max_length=50, unique=True),
        ),
    ]
