# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-11 12:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20171111_1258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seentvshows',
            old_name='movie',
            new_name='tv_show',
        ),
    ]
