# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20171111_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvshowcollections',
            name='content',
            field=models.ManyToManyField(related_name='collection_tv_shows', to='api.TVShows', verbose_name='list_of_tv_shows'),
        ),
    ]
