# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-14 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20171014_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='tmdbId',
            field=models.IntegerField(default=0),
        ),
    ]
