# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20171112_0904'),
    ]

    operations = [
        migrations.CreateModel(
            name='Networks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=1000)),
                ('tmdbId', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='tvshows',
            name='directors',
        ),
        migrations.AddField(
            model_name='tvshows',
            name='networks',
            field=models.ManyToManyField(to='api.Networks', verbose_name='list_of_directors'),
        ),
    ]
