# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_movies_seen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=1000)),
                ('hash', models.CharField(default='', max_length=128)),
                ('movies', models.ManyToManyField(to='api.Movies', verbose_name='list_of_movies')),
            ],
        ),
    ]
