# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-16 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20171112_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviecollections',
            name='poster_language',
            field=models.CharField(default='-', max_length=2),
        ),
        migrations.AddField(
            model_name='moviecollections',
            name='title_language',
            field=models.CharField(default='en', max_length=2),
        ),
        migrations.AddField(
            model_name='moviecollections',
            name='unseen_titles',
            field=models.BooleanField(default=0),
        ),
    ]
