# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-16 09:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20171116_0907'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moviecollections',
            old_name='unseen_titles',
            new_name='hide_unseen_titles',
        ),
        migrations.RenameField(
            model_name='tvshowcollections',
            old_name='unseen_titles',
            new_name='hide_unseen_titles',
        ),
    ]
