# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20171017_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collections',
            name='movies',
            field=models.ManyToManyField(related_name='collection_movies', to='api.Movies', verbose_name='list_of_movies'),
        ),
    ]
