# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 16:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20171018_1053'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionMovies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen', models.BooleanField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='collections',
            name='movies',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='seen',
        ),
        migrations.AddField(
            model_name='collectionmovies',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Movies'),
        ),
    ]
