# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-16 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20171116_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='original_language',
            field=models.CharField(default='', max_length=4),
        ),
    ]
