# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-18 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_movies_original_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Titles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=1000)),
                ('language', models.CharField(default='', max_length=4)),
            ],
        ),
        migrations.RemoveField(
            model_name='movies',
            name='title',
        ),
        migrations.AddField(
            model_name='movies',
            name='titles',
            field=models.ManyToManyField(to='api.Titles', verbose_name='list_of_titles'),
        ),
    ]
