# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-18 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20171118_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(default='', max_length=200)),
                ('language', models.CharField(default='', max_length=4)),
            ],
        ),
        migrations.RemoveField(
            model_name='movies',
            name='poster',
        ),
        migrations.AddField(
            model_name='movies',
            name='posters',
            field=models.ManyToManyField(to='api.Posters', verbose_name='list_of_posters'),
        ),
    ]
