# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 18:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_collections_movies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectionmovies',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='collections',
            name='movies',
        ),
        migrations.DeleteModel(
            name='CollectionMovies',
        ),
    ]
