# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-18 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20171118_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tvshows',
            name='poster',
        ),
        migrations.RemoveField(
            model_name='tvshows',
            name='title',
        ),
        migrations.AddField(
            model_name='tvshows',
            name='original_language',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AddField(
            model_name='tvshows',
            name='posters',
            field=models.ManyToManyField(to='api.Posters', verbose_name='list_of_posters'),
        ),
        migrations.AddField(
            model_name='tvshows',
            name='titles',
            field=models.ManyToManyField(to='api.Titles', verbose_name='list_of_titles'),
        ),
    ]
