# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20171019_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='collections',
            name='movies',
            field=models.ManyToManyField(related_name='collection_movies', to='api.Movies', verbose_name='list_of_movies'),
        ),
    ]
