# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_seenmovies'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=1000)),
                ('tmdbId', models.IntegerField(default=0)),
            ],
        ),
    ]
