# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='genres',
            field=models.ManyToManyField(to='api.Genres', verbose_name='list_of_genres'),
        ),
    ]
