# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_movies_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='note',
            field=models.IntegerField(default=0),
        ),
    ]
