# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_movies_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='note',
            field=models.FloatField(default=0),
        ),
    ]
