# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20171020_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='poster',
            field=models.CharField(default='', max_length=200),
        ),
    ]
